apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1591614987
    meta.helm.sh/release-namespace: optishop
  creationTimestamp: "2020-06-08T11:16:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.4.0
    component: server
    heritage: Helm
    release: prometheus-1591614987
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
      f:status:
        f:phase: {}
    manager: Go-http-client
    operation: Update
    time: "2020-06-08T11:16:29Z"
  name: prometheus-1591614987-server
  namespace: optishop
  resourceVersion: "712529"
  selfLink: /api/v1/namespaces/optishop/persistentvolumeclaims/prometheus-1591614987-server
  uid: b108de79-3082-47b5-9b68-8a5a6809bfc1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending
