apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: puchoborja/scraper:0.0.3
        #args:
        # - sleep
        # - "9999"
        volumeMounts:
        - name: scraper-volume
          mountPath: /work/config
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8090"
        - name: QUARKUS_DATASOURCE_URL
          value: "vertx-reactive:postgresql://10.104.4.57:5432/scraperdb"
        - name: QUARKUS_DATASOURCE_USERNAME
          value: "scraper"
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: "password"
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: scraper-volume
        configMap:
          name: scraper-config

---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: NodePort
  selector:
    app: scraper
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30068
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: optishop.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: scraper-service
          servicePort: 8090


