apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: pucho/scraper:0.0.1
        ports:
        - containerPort: 80

